config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :companies, only: %i[ new edit update create]
  resources :positions
  resources :applicants, only: %i[ index new create]
  root "home#index"
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :user
  belongs_to :position
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :positions
  validates :name, :url, presence: true
  has_one_attached :logo
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :company
  validates :name, :summary, :description, presence: true
  enum career: { developer: 0, business_inteligence: 1,
                information_technology: 2, designer: 3 }
  enum contract: { clt: 0, pj: 1, both: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :company
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = current_user.build_company
  end

  def create
    @company = current_user.build_company(company_params)
    debugger
    if @company.save
      flash[:notice] = "Empresa criada com sucesso!"
      redirect_to root_path
    else
      flash[:error] = "Empresa não foi criada"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @company = current_user.company
    if @company.update(company_params)
      flash[:notice] = "Empresa criada com sucesso!"
      redirect_to root_path
    else
      flash[:error] = "Empresa não foi criada"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @company = current_user.company
  end

  def company_params
    params.require(:company).permit(:name, :url, :logo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @positions = Position.where(publish: true).order(created_at: :desc)
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_company
  before_action :set_position, only: [ :edit, :show, :update, :destroy ]
  def index
    @positions = @company.positions
  end

  def new
    @position = @company.positions.new
  end

  def create
    @position = @company.positions.new(position_params)
    debugger
    if @position.save
      flash[:notice] = "Vaga criada com sucesso!"
      redirect_to positions_path
    else
      flash[:alert] = "Erro ao criar a Vaga!"
      render :new, status: :unprocessable_entity
    end
  end

  def edit;end

  def show;end

  def update
    if @position.update(position_params)
      flash[:notice] = "Vaga atualizada com sucesso!"
      redirect_to positions_path
    else
      flash[:alert] = "Erro ao atualizar a Vaga!"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
  end

  private

  def set_company
    @company = current_user.company
  end

  def set_position
    @position = @company.positions.find(params[:id])
  end

  def position_params
    params.require(:position).permit(:name, :career, :contract, :remote, :city, :state, :summary, :description, :publish)
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def dinamic_url
    if current_user.company.present? && current_user.company.try(:id).present?
      edit_company_path(current_user.company)
    else
      new_company_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/application/edit.html.erb
<%= render 'form' %>

app/views/application/new.html.erb
<%= render 'form' %>

app/views/companies/_form.html.erb
<div class="row py-5">
  <div class="card">
      <div class="card-header">
        <%= @company.new_record? ? "Nova empresa" : "Editar empresa #{@company.name}" %>
      </div>
      <div class="card-body">
        <%= simple_form_for @company do |f| %>
          <%= f.error_notification %>

          <%= f.input :name %>
          <%= f.input :url %>
          <%= image_tag(url_for(@company.logo), class: 'logo') unless @company.new_record? && !@company.logo.nil? %>
          <%= f.file_field :logo %>
      </div>
        <div class="card-footer">
          <%= f.button :submit, class: 'btn btn-success' %>
        </div>
      <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="row py-5">
  <% @positions.each do |position| %>
  <div class="card">
    <card class="card-header d-flex justify-content-between">
      <%= position.name %>
      <strong> Empresa: </strong>
      <%= position.company.name %>
    </card>
    <div class="card-body">
      <%= position.summary %>
    </div>
    <div class="card-footer">
      <%= link_to "detalhes da vaga" , position_path(position) %>
    </div>
  </div>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Open Vagas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Open Vagas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/positions/_form.html.erb
<div class="row py-5">
  <div class="card">
      <div class="card-header">
        <%= @position.new_record? ? "Nova vaga" : "Editar vaga #{@position.name}" %>
      </div>
      <div class="card-body">
        <%= simple_form_for @position, data: { turbo: false } do |f| %>
        <div class="form-group">
          <%= f.input :name, label: t('activerecord.attributes.position.name') %>
        </div>
        <div class="form-group">
          <%= f.input :career, label: t('activerecord.attributes.position.career'), as: :select, collection: Position.careers.keys.map { |c| [t("activerecord.enums.position.career.#{c}"), c] }, include_blank: false %>
        </div>
        <div class="form-group">
          <%= f.input :contract, label: t('activerecord.attributes.position.contract'), as: :select, collection: Position.contracts.keys.map { |c| [t("activerecord.enums.position.contract.#{c}"), c] } %>
        </div>
        <div class="form-check">
          <%= f.input :remote, label: t('activerecord.attributes.position.remote'), as: :boolean %>
        </div>
        <div class="form-group">
          <%= f.input :city, label: t('activerecord.attributes.position.city') %>
        </div>
        <div class="form-group">
          <%= f.input :state, label: t('activerecord.attributes.position.state') %>
        </div>
        <div class="form-group">
          <%= f.input :summary, label: t('activerecord.attributes.position.summary') %>
        </div>
        <div class="form-group">
          <%= f.input :description, label: t('activerecord.attributes.position.description') %>
        </div>
        <div class="form-check">
          <%= f.input :publish, label: t('activerecord.attributes.position.publish'), as: :boolean %>
        </div>
        <div class="form-group">
          <%= f.association :company, label: t('activerecord.attributes.position.company'), disabled: true %>
        </div>
      </div>
        <div class="card-footer">
          <%= f.button :submit, class: 'btn btn-success' %>
        </div>
      <% end %>
  </div>
</div>

app/views/positions/index.html.erb
<!-- app/views/positions/index.html.erb -->
<h2 class=" d-flex py-5 justify-content-center">Lista de Vagas</h2>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Carreira</th>
      <th>Contrato</th>
      <th>Remoto</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th>Publicado</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.name %></td>
        <td><%= position.career %></td>
        <td><%= position.contract %></td>
        <td><%= position.remote ? 'Sim' : 'Não' %></td>
        <td><%= position.city %></td>
        <td><%= position.state %></td>
        <td><%= position.publish ? 'Sim' : 'Não' %></td>
        <td>
          <%= link_to 'Visualizar', position_path(position), class: 'btn btn-info' %>
          <%= link_to 'Editar', edit_position_path(position), class: 'btn btn-warning' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('positions.index.new'), new_position_path, class: 'btn btn-primary' %>

app/views/positions/show.html.erb
<div class="container py-5">
  <div class="card">
    <div class="card-header">
      <h3><%= @position.name %></h3>
    </div>
    <div class="card-body">
      <p><strong><%= t('activerecord.attributes.position.career') %>:</strong> 
        <%= t("activerecord.enums.position.career.#{@position.career}") %></p>

      <p><strong><%= t('activerecord.attributes.position.contract') %>:</strong> 
        <%= t("activerecord.enums.position.contract.#{@position.contract}") %></p>

      <p><strong><%= t('activerecord.attributes.position.remote') %>:</strong> 
        <%= @position.remote? ? t('activerecord.attributes.remote.yes') : t('activerecord.attributes.remote.no') %></p>

      <p><strong><%= t('activerecord.attributes.position.city') %>:</strong> <%= @position.city %></p>
      <p><strong><%= t('activerecord.attributes.position.state') %>:</strong> <%= @position.state %></p>

      <p><strong><%= t('activerecord.attributes.position.summary') %>:</strong></p>
      <p><%= @position.summary %></p>

      <p><strong><%= t('activerecord.attributes.position.description') %>:</strong></p>
      <p><%= @position.description %></p>

      <p><strong><%= t('activerecord.attributes.position.publish') %>:</strong> 
        <%= @position.publish? ? t('yes') : t('no') %></p>

      <p><strong><%= t('activerecord.attributes.position.company') %>:</strong> <%= @position.company.name %></p>
    </div>

    <div class="card-footer">
      <%= link_to t('buttons.edit'), edit_position_path(@position), class: 'btn btn-primary' %>
      <%= link_to t('buttons.delete'), position_path(@position),  data: { turbo_method: 'delete', turbo_confirm: t('messages.confirm_delete') }, class: 'btn btn-danger' %>
      <%= link_to t('buttons.back'), positions_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="container-flouid">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">
        <h3>Open Vagas</h3>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Minha Empresa",dinamic_url, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Vagas",positions_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Blog</a>
            </li>

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Event</a>
            </li>

          </ul>
            <%= link_to current_user.email, edit_user_registration_path(current_user), class: "btn btn-outline-primary mr-2" %>
            <%= link_to "Logout", destroy_user_session_path(current_user), data: { turbo_method: 'delete', turbo_confirm: 'Tem certeza?' }, class: "btn btn-outline-primary m-2" %>
          <% else %>
            <%= link_to "Login",new_user_session_path, class: "btn btn-outline-primary mr-2" %>
        <% end %>

      </div>
    </div>
  </nav>
</div>